apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-injector
  labels:
    app: secrets-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-injector
  template:
    metadata:
      labels:
        app: secrets-injector
    spec:
      serviceAccountName: secrets-injector
      containers:
        - name: secrets-injector
          image: 1password/kubernetes-secrets-injector:latest
          imagePullPolicy: IfNotPresent
          args:
          - -service-name=secrets-injector
          - -logtostderr
          - -v=4
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "/prestop.sh" ]
