name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']   # run for PRs targeting any branch (main and others)
    paths-ignore: &ignore_paths
      - 'docs/**'
      - '*.md'
      - '.golangci.yml'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches: [ main ]
    paths-ignore: *ignore_paths

concurrency:
  group: e2e-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true # cancel previous job runs for the same branch

jobs:
  e2e-test:
    uses: ./.github/workflows/e2e-tests.yml
    secrets:
      OP_CONNECT_CREDENTIALS: ${{ secrets.OP_CONNECT_CREDENTIALS }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
