name: Test E2E

on:
  push:
    branches: [ main ]
    paths-ignore: &ignore_paths
      - 'docs/**'
      - '*.md'
      - '.golangci.yml'
      - '.gitignore'
      - 'LICENSE'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']   # run for PRs targeting any branch (main and others)
    paths-ignore: *ignore_paths

concurrency:
  group: e2e-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true # cancel previous job runs for the same branch

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from external contributor
        if: github.event_name == 'pull_request'
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "❌ External PR detected. This workflow requires approval from a maintainer."
            echo "Please ask a maintainer to run '/ok-to-test' command to trigger the fork workflow."
            exit 1
          fi
          echo "✅ Internal PR detected. Proceeding with tests."

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod tidy

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kubernetes-secrets-injector-test-e2e

      - name: Create '1password-credentials.json' file
        env:
          OP_CONNECT_CREDENTIALS: ${{ secrets.OP_CONNECT_CREDENTIALS }}
        run: |
          echo "$OP_CONNECT_CREDENTIALS" > 1password-credentials.json

      - name: Run E2E tests
        run: make test-e2e
        env:
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
