name: E2E tests [fork]

on:
  repository_dispatch:
    types: [ ok-to-test-command ]

permissions:
  contents: read

concurrency:
  group: e2e-fork-${{ github.event.client_payload.pull_request.number || github.run_id }}
  cancel-in-progress: true # cancel previous job runs for the same branch

jobs:
  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.args.named.sha != '' &&
      contains(
        github.event.client_payload.pull_request.head.sha,
        github.event.client_payload.slash_command.args.named.sha
      )
    secrets:
      OP_CONNECT_CREDENTIALS: ${{ secrets.OP_CONNECT_CREDENTIALS }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
